_core:
  default_config_hash: O3rsbjEveBvnof1Hdq3ih8UBqlRN2betEk9OZhaiTPM
tac_lite_categories:
  cliente: cliente
tac_lite_schemes: '1'
menu_rebuild_needed: true
tac_lite_config_scheme_1:
  name: 'Acceso cliente'
  perms:
    grant_view: grant_view
    grant_update: grant_update
  unpublished: 0
  term_visibility: 0
  tac_lite_create: 0
tac_lite_grants_scheme_1:
  anonymous:
    cliente: {  }
  authenticated:
    cliente: {  }
  content_editor:
    cliente: {  }
  client_admin:
    cliente: {  }
  administrator:
    cliente: {  }
